version: '3.2'
services:
  app:
    build: './docker/app'
    volumes:
      - './:/app'
      - '/etc/letsencrypt:/etc/letsencrypt'
    networks:
      default:
        aliases:
         - node-solid-server
networks:
  default:
    external:
      name: nginx-agora
